---
- name: Kubeadm Control Init
  become: true
  hosts: all
  remote_user: carlos
  gather_facts: no
  tasks:
    - import_tasks: base-node.yaml
    # Create cluster
    - name: Create Cluster Control Plane node
      shell: |
        kubeadm init --control-plane-endpoint=k8s.cadumillani.com.br --token {{ k8s_secret }} --token {{ k8s_secret }}
    - name: Configure CNI
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"