---
- name: Kubeadm Worker Join
  become: true
  hosts: all
  remote_user: carlos
  gather_facts: no
  tasks:
    - import_tasks: base-node.yaml
    - name: Join Worker
      shell: |
        kubeadm join k8s.cadumillani.com.br:6443 --token {{ k8s_secret }} --discovery-token-unsafe-skip-ca-verification
      when: "{{ is_worker }}"
    - name: Join Control
      shell: |
        kubeadm join k8s.cadumillani.com.br:6443 --token {{ k8s_secret }} --certificate-key {{ k8s_key }} --control-plane --discovery-token-unsafe-skip-ca-verification
      when: "{{ is_worker }} == false"