# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "cadu-homelab-iac-state"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "us-east-2"
  }
}
